### jupyter notebook實用快捷鍵：

<pre>
cmd + shift + P  顯示所有指令和快捷鍵
shift + enter    執行目前的cell
enter            切換到編輯模式（藍色cell外框）
esc              跳出編輯模式（綠色cell外框）
esc, double d    刪除這個cell
esc, a           往上插入一個cell
esc, b           往下插入一個cell
esc, m           將目前cell改為Markdown
</pre>

### 開啟ipython console，可用<code>whos</code>指令檢查所有變數

In [1]:
%qtconsole

### Print出tensor的內容

In [4]:
import tensorflow as tf

myTensor = tf.truncated_normal([7, 3], -0.1, 0.1)
with tf.Session():
    print(myTensor.eval())

[[-0.05391058  0.08315045 -0.13529134]
 [-0.23896462 -0.26369727 -0.21258667]
 [-0.08623524 -0.25418624 -0.14715655]
 [-0.03482413 -0.00730048 -0.11344711]
 [-0.13682854 -0.06836341 -0.03585137]
 [-0.1620221  -0.15014869 -0.14201401]
 [-0.15404423 -0.12774941 -0.0852775 ]]


### 使用Pickle在檔案間分享巨大資料（以dictionary為例）

In [9]:
# 輸出pickle檔至./目錄
# /file_a.py
import pickle
myDict = {'a':'apple','b':'banana'}
pickle.dump( myDict, open( "./myDict.p", "wb" ) )


# 讀入./目錄的pickle檔
# /file_b.py 
import pickle
myDict = pickle.load( open( "./myDict.p", "rb" ) )
print(myDict)

{'a': 'apple', 'b': 'banana'}
